### ISSUE TITLE
Keep chainId at just a single place

### ISSUE THREAD

**Issue by atvanguard** [maticnetwork/contracts#121]
Requires minor refactoring.

**Comment by 0xAshish** [comment]
@atvanguard actually it was at a single place in the beginning 😆

**Comment by atvanguard** [comment]
Well, do you think the reason could be that "in the beginning", 
1. childERC20 / childerc721 tokens did not know how to execute `transferWithSig` orders for marketplace. That was added [here](https://github.com/maticnetwork/contracts/commit/063afae462018d775c913dac96016bd531123b25#diff-8b3380305aa026a2720ad3b6b3973c0e).

2. We did not have marketplace predicate.
3. We did not have tests for marketplace predicate.

There is no way you would end up having that duplicated across several files 🤣

**Comment by cumpsty** [comment]
I'm interested in helping out. Is this a good issue to get started with? Anything I should know?

**Comment by atvanguard** [comment]
Hey @cumpsty Thanks for the interest! Glad to hear you'd like to work on it.

> Anything I should know?

Nothing specific, just check all the places chainId is being used in contracts and let's keep that at in a single place that others can inherit from. Same for tests.

**Comment by atvanguard** [comment]
Hey Cumpsty,
Sorry we needed this done soon, so I rolled out a fix. Happy to help on any other feature you'd like to work on.
