### ISSUE TITLE
Add priority queue and marketplace for faster exits

### ISSUE THREAD

**Issue by jdkanani** [maticnetwork/contracts#13]
- [x] Add priority queue for each token
- [x] Create an `exit` object when the user asks for the `exit`. Need to check if tx is included and balance is valid.
- [x] Create `challengeExit` or equivalent method to challenge invalid/double spent transaction 
- [x] Add `finalizeExit` or equivalent method to process exits
- [x] Add test-case for whole exit process

**Comment by jdkanani** [comment]
Implemented in #16

**Comment by shogochiai** [comment]
@jdkanani I guessed burntExit's exitNFT's discount rate would be very fair&small because burnProof is to be the guarantee of withdrawal. Is this assumption correct? (Or any possible challenge for burntExit?)

**Comment by jdkanani** [comment]
@shogochiai Yes. Mostly, that will be instant with liquidity pools or Dharma underwriting (99.99%)!

**Comment by jdkanani** [comment]
We will also provide a way where withdraw/sell will happen in one transaction.
