### ISSUE TITLE
Add bond for exit and reward challenger

### ISSUE THREAD

**Issue by jdkanani** [maticnetwork/contracts#17]
While starting an exit, an exitNFT's owner will put small bond and challenger will get that bond if challenge gets accepted.

Question - is there any way we can avoid exit bond?

**Comment by atvanguard** [comment]
Plasma/Matic newbie here 🙋‍♂️ so if I make no sense. Trying to learn more.

I understand that attempting to withdraw a particular token from the matic chain would entail providing a _proof of burn_ on the matic chain to the main contract. This withdrawl request will remain open for someone to challenge. By providing a bond, the Idea is to disincentivize an actor from submitting  submitting an invalid withdrawl request and to incentivize a challenger to catch bad withdrawl requests. Is it correct?

**Comment by 0xAshish** [comment]
@atvanguard yup, also we can use this amount to decide the priority for exit(yet to be researched).

**Comment by atvanguard** [comment]
https://github.com/maticnetwork/contracts/pull/78#issuecomment-498642475

- Exiting with burnt tokens (happy case) requires ~ 400k gas.
- MoreVP exits require gas in the range of ~ 470k - 700k
700k * 100 gwei = 0.07 eth. How about we keep the bond at 0.1 eth for MoreVP style exits and no bond for `startExitWithBurntTokens`

**Comment by jdkanani** [comment]
Looks good to me. 

However, can we have dynamic bonds? But, it will adds more complexity I guess.

**Comment by atvanguard** [comment]
Dynamic how?
