### ISSUE TITLE
add state transition checks to challengeExit() function

### ISSUE THREAD

**Issue by johannbarbie** [maticnetwork/contracts#22]
how otherwise do you prevent exits of spent funds?

**Comment by jdkanani** [comment]
We have separate file for challenges - https://github.com/maticnetwork/contracts/blob/master/contracts/proofs/ExitValidator.sol

**Comment by johannbarbie** [comment]
i see in that function that you validate only `require(exitId2 > exitId);`, but not the transaction signature or if the state transition is valid.

Here is how an operator can attack you:
1. user registers transaction for exit
2. operator includes transfer to him with invalid signature (you don't check it)
3. operator cancel's user's exit.

**Comment by johannbarbie** [comment]
In plasma the signature checking is not optional:

https://github.com/omisego/plasma-mvp/blob/master/plasma/root_chain/contracts/RootChain.sol#L241

it establishes the security of the chain, as it checks a valid state transition.

**Comment by jdkanani** [comment]
This one? https://github.com/maticnetwork/contracts/blob/master/contracts/proofs/ExitValidator.sol#L45

**Comment by johannbarbie** [comment]
oh, nice :)
but let's dig deeper:

1. user A sends transaction to user B
2. operator C includes transfer, but modifies events to show that money went to C
3. user A notices the invalid state transition, and registers his transfer for exit
4. C slashes A's exit

where do you validate that based on the transaction content the right events have been emitted?

**Comment by johannbarbie** [comment]
i see that here you check if transaction root and receipt root included in same block:
https://github.com/maticnetwork/contracts/blob/master/contracts/mixin/RootChainValidator.sol#L44-L46
but i think you also need to check that from the transaction the receipt got created correctly.

**Comment by jdkanani** [comment]
Yeah definitely. That’s where file https://github.com/maticnetwork/contracts/blob/master/contracts/proofs/ERC20Validator.sol will be used

**Comment by johannbarbie** [comment]
ok, this file is not used anywhere in your current Plasma contract implementation, right?

as i understand you are comparing `msg.data` to receipt data here.

few questions come to mind:
- how do you know the user actually has the funds? wouldn't i be able to collude with the operator and spend more funds than i have?
- what if the contract implements any conditions? like a security token where only KYC'd users can receive funds, wouldn't you need to check such conditions?

**Comment by jdkanani** [comment]
Rootchain has `addValidator` method which will add validators as Rootchain was growing and `gasLimit` was the problem. In future, we will change owner to `0x` after deployment or use governance. Though, in the case of governance, we haven't put any thoughts on this part. We are also looking towards other projects to see how plasma will upgrade or fix production bugs. Any help/advice would be appreciated.

> How do you know the user actually has the funds? wouldn't I be able to collude with the operator and spend more funds than I have?

I am also not sure if UTXO based one also has a solution to this problem. A user has to watch chain and if they detect such fraud they start Exit process. Any suggestions?

> what if the contract implements any conditions? like a security token where only KYC'd users can receive funds, wouldn't you need to check such conditions?

Only simple transfer with plasma exit/challenge for now. But we would love to add those things.

**Comment by jdkanani** [comment]
One thing just came in my mind is to add Merkle root of (token -> Merkle of Root <allowed users>) and use that to challenge. (Again, haven't put many thoughts on this. Thought of it on the fly :)

**Comment by johannbarbie** [comment]
> Rootchain was growing and gasLimit was the problem.

are you saying that the contract became too big? hence the transition checking has been taken out?

> I am also not sure if UTXO based one also has a solution to this problem.

the difference is that in the UTXO model you compare specific outputs to inputs. in the account model it is not clear what i would need to check to see if the balance of an account is correct. have you thought about merkle sum trees or other ways to relate between the different transactions?

**Comment by johannbarbie** [comment]
> Only simple transfer with plasma exit/challenge for now.

so on the matic sidechain, there can only be one `certified` ERC20 implementation where none of the token holders can be contracts?

why allow any other transactions than in these certified ERC20 contracts? wouldn't it just open a window for the operator to flood users with garbage transactions, until users can not keep up to validate everything, then the operator sneaks in invalid state transitions, based on which he can then steal funds from the users?

**Comment by jdkanani** [comment]
> are you saying that the contract became too big? hence the transition checking has been taken out?

We created separated contracts and they will call each other.

> the difference is that in the UTXO model you compare specific outputs to inputs

Are you talking about in validator node or in the Rootchain contract? I am not sure if PlasmaMVP checks UTXO's previous inputs' output when you exit.

**Comment by johannbarbie** [comment]
> I am not sure if PlasmaMVP checks UTXO's previous inputs' output when you exit.

i think i'm talking about users, that need to check the chain all the time. in UTXO all the data they need is in the block. In the account model they need to know all the data of all accounts since the beginning of time. basically users will need to run full nodes in the browser, right?

**Comment by jdkanani** [comment]
> why allow any other transactions than in these certified ERC20 contracts? wouldn't it just open a window for the operator to flood users with garbage transactions, until users cannot keep up to validate everything, then the operator sneaks in invalid state transitions, based on which he can then steal funds from the users?

A user can also validate tx which is relevant or I am missing something. The node should take care of it.

**Comment by jdkanani** [comment]
> I think I'm talking about users, that need to check the chain all the time. in UTXO all the data they need is in the block. In the account model they need to know all the data of all accounts since the beginning of time. basically users will need to run full nodes in the browser, right?

I think the user can have simple latest state of (if users need it in any form example - Merkle sum as you mentioned) which they need and use it to get data instead of storing the whole chain. You can do same in UTXO (where you keep only unspent TXs).

**Comment by johannbarbie** [comment]
if you implement transition checking in `challengeExit()`, i see that you can do accounting for a specific, limited type of ERC20 contract.

I see a few disadvantages:
- cumbersome, expensive implementation
- potentially unbounded validator effort for users

but that is not point of this issue. I think it can be closed once ERC20Validator.sol  is implemented in `challengeExit()`.

**Comment by atvanguard** [comment]
Hey @johannbarbie 
Thanks for a detailed review! Since this discussion, we have made major changes to our plasma design. We are implementing the [Plasma predicate pattern](https://plasma.build/t/predicates-in-matic-plasma/86).

In this pattern, the state transition checks are delegated to the predicate that understands whether state transitions (for instance, funds were spent) are outdated. See [verifyDeprecation](https://github.com/maticnetwork/contracts/blob/dev-morevp/contracts/root/predicates/ERC20Predicate.sol#L103) in the ERC20Predicate.

The `challengeExit` function in `withdrawManager` calls `verifyDeprecation` in the correct predicate and cancels the exit if deemed to be outdated. See [this](https://github.com/maticnetwork/contracts/blob/dev-morevp/contracts/root/withdrawManager/WithdrawManager.sol#L177).

The signature on the challenge tx is validated [here](https://github.com/maticnetwork/contracts/blob/dev-morevp/contracts/root/predicates/ERC20Predicate.sol#L111) and the fact that state transitions were correct is verified [here](https://github.com/maticnetwork/contracts/blob/dev-morevp/contracts/root/predicates/ERC20Predicate.sol#L125) - 3rd parameter (`signer` / `participant`) in the call to `processReferenceTx` is of essence. We are also seeking review from the plasma community on the [pull request](https://github.com/maticnetwork/contracts/pull/78) as well.

Note: The above links will break once the pull request is merged and the branch is deleted.
