### ISSUE TITLE
Non-compliance mandatory tokenFallback

### ISSUE THREAD

**Issue by Agusx1211** [maticnetwork/contracts#24]
https://github.com/maticnetwork/contracts/blob/e59e3fb9f7b4ed946e50dccb59a5b4b4d53685fa/contracts/token/StandardToken.sol#L22

With this modification the StardardToken forces the contracts receiving tokens to implement the tokenFallback method; this causes the StandardToken.sol not to follow the ERC20 standard.

I believe this method is meant to replicate the mandatory fallback on the Ethereum network, if that is the case, may be a good idea to move this to MaticWETH.sol

Another possible solution is making a nonThrow call to tokenFallback and ignore a potential failure, that will not replicate the functionality of the mandatory fallback, but it will be ERC20 compliance.

**Comment by jdkanani** [comment]
Nice catch. But we are using `MaticWETH` for testing - that will never be on the main chain. We will use the same WETH.sol as deployed by radar/0x https://weth.io/. This StandardToken will only be used in `ChildERC20` only.

**Comment by jdkanani** [comment]
@Agusx1211 Closing this issue. Reopen if you have more questions.
