### ISSUE TITLE
Represent PoS slot as NFT

### ISSUE THREAD

**Issue by jdkanani** [maticnetwork/contracts#27]
Current implementation: https://github.com/maticnetwork/contracts/pull/26

Can we represent PoS validator slot as NFT?

As a validator node owner, one can sell slot on open market without through decentralized exchanges (@0xproject) or marketplace (like OpenSea). That way one doesn't have to wait for 2-4 dynasty for rewards or exit.

**Comment by jdkanani** [comment]
@0xAshish Let's start this with new economics @sandeepnailwal

**Comment by 0xAshish** [comment]
almost finish with implementation, PR: https://github.com/maticnetwork/contracts/pull/50

**Comment by 0xAshish** [comment]
closing the issue feature branch is merged https://github.com/maticnetwork/contracts/pull/50
