### ISSUE TITLE
Add conditions for leave/join events for stakeholders

### ISSUE THREAD

**Issue by jdkanani** [maticnetwork/contracts#4]
Following are conditions to leave/join PoS system - 

- [x] Add epoch for 100 header blocks 
- [x] Add minimum and maximum stake amount
- [x] Add minimum lock-in period (in terms of the number of the epoch)
- [x] Leave request
- [x] Minimum time period (in terms of the number of the epoch) between leave request and actual leave event (+ refund stake amount)

**Comment by vaibhavchellani** [comment]
@jdkanani is this something that has to be implemented ? happy to take it

**Comment by jdkanani** [comment]
@ashishrp has started working on this. @vaibhavchellani let's discuss next steps on this one.

**Comment by 0xAshish** [comment]
@jdkanani @vaibhavchellani these all tasks have been checked in new PoS PR.

**Comment by 0xAshish** [comment]
the maximum stake is decided through free-market inflation.

**Comment by 0xAshish** [comment]
@jdkanani we can close this issue.
