### ISSUE TITLE
Error with Transaction

### ISSUE THREAD

**Issue by damianlluch** [maticnetwork/contracts#407]
```
if (typeof web3 !== 'undefined' && amount !== null && amount > 0)  {
            window.web3 = new Web3(Web3.givenProvider)
            const chainId = await window.web3.eth.getChainId()
            if (chainId !== 80001) {
                alert('conecte metamask a polygon testnet')
            } else {
                const chainIdDec = await window.web3.eth.getChainId();
                await window.ethereum.enable();
                const accounts = await window.ethereum.request({ method: 'eth_requestAccounts' });
                const account = accounts[0];
                let balanceInWei = await window.web3.eth.getBalance(account)
                let balance = Number(window.web3.utils.fromWei(balanceInWei, 'ether')).toFixed(2)
                let amountInWei = window.web3.utils.toWei(amount, 'ether')
                console.log(amountInWei)
                console.log(balanceInWei)
                console.log(amount)
                console.log(amountInWei)
                const transactionParameters = {
                    nonce: '0x00', // ignored by MetaMask
                    to: '0x70997970C51812dc3A010C7d01b50e0d17dc79C8', // Required except during contract publications.
                    from: account, // must match user's active address.
                    value: amountInWei, // Only required to send ether to the recipient from the initiating external account.
                    chainId: chainIdDec, // Used to prevent transaction reuse across blockchains. Auto-filled by MetaMask.
                };
                console.log('sending tx')
                window.ethereum.request({
                    method: 'eth_sendTransaction',
                    params: [transactionParameters],
                }).then((txHash) => console.log(txHash))
                  .catch((error) => console.log('error', error));
            }
        }
        ```
        
        
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/1463804/165698528-1246c445-23eb-4186-9635-3217e43eaec2.png">

        
        Hello! I don't know if this is the right place to ask this question. But I am having a problem sending a transaction to Polygon.
It's the first time I use the network, and when I pass to wei the amount I want to send, it turns into a meaningless number...
I've done some research, and I've seen examples where other devs convert to gwei with different decimal... I'm not sure what's the way.
If you can help me.

thanks

**Comment by jdkanani** [comment]
Wrong forum to post the issue.

**Comment by damianlluch** [comment]
> Wrong forum to post the issue.

Can you complete your work and tell me where I should publish?

**Comment by MaticParvez** [comment]
Hello @damianlluch Can you please post this query on support.polygon.technology and we will assist you accordingly.

**Comment by damianlluch** [comment]
> Hello @damianlluch Can you please post this query on support.polygon.technology and we will assist you accordingly.

thanks @MaticParvez

**Comment by damianlluch** [comment]
> > Hello @damianlluch Can you please post this query on support.polygon.technology and we will assist you accordingly.
> 
> thanks @MaticParvez

I have tried to pass the captcha at least 10 times and it was impossible. I could not register. I leave it as a comment...

**Comment by MaticParvez** [comment]
Lets connect over telegram my id is Parvez03
