### ISSUE TITLE
ERC223 bridge support

### ISSUE THREAD

**Issue by laurent387** [maticnetwork/contracts#411]
Hello
Implement token ERC223 for the native polygon bridge
Bounty : 5000 [SaTT](https://www.satt.io/)
Thanks

**Comment by geoffreymoya** [comment]
the right solidity function is : tokenFallback(address,uint,bytes32 ) pure public 
it must be implemented by contract that operate transferFrom()

**Comment by jdkanani** [comment]
One can use fx-portal to implement it - https://github.com/fx-portal/contracts
