### ISSUE TITLE
`npm install` fails

### ISSUE THREAD

**Issue by atvanguard** [maticnetwork/contracts#54]
```
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
```
This is a known issue with older version of `nan` package (<= 2.7) with newer versions of node (>= 10).

**Comment by 0xAshish** [comment]
please try it with node@8.11.3. some crypto packages are on node8.

**Comment by atvanguard** [comment]
Fix is trivial. do you think regenerating package-lock could have issues?

**Comment by 0xAshish** [comment]
will see if anything fails in CI(should work fine), thanks for PR 👍.
