### ISSUE TITLE
Make deposits pause-able 

### ISSUE THREAD

**Issue by atvanguard** [maticnetwork/contracts#60]
1. A master switch to pause deposits.
This is to prevent new users from depositing funds in the plasma contract if something is not right on the side chain.

2. If a checkpoint has not been submitted for a specified duration, it should be possible to mark the side chain as halted on the root chain. After that no more checkpoints can be submitted and the deposits will be paused as well.

**Comment by 0xAshish** [comment]
@atvanguard some details would be better. 😄

**Comment by jdkanani** [comment]
We should have way to pause deposit (at-least deposit)

**Comment by jdkanani** [comment]
@atvanguard did you add support for this?

**Comment by atvanguard** [comment]
Not yet! Will rollout independent of other changes.
