### ISSUE TITLE
Add `ERC-165` into rootchain contracts

### ISSUE THREAD

**Issue by 0xAshish** [maticnetwork/contracts#89]
since we are adding so many EIPs/interfaces it makes sense that we add `ERC-165`.

**Comment by atvanguard** [comment]
What does it mean? ERC165 simply implements an interface lookup table.
```
interface IERC165 {
    /**
     * @notice Query if a contract implements an interface
     * @param interfaceId The interface identifier, as specified in ERC-165
     * @dev Interface identification is specified in ERC-165. This function
     * uses less than 30,000 gas.
     */
    function supportsInterface(bytes4 interfaceId) external view returns (bool);
}
```

**Comment by 0xAshish** [comment]
>ERC165 simply implements an interface lookup table
yup, so basically it makes contract to contract communication easier.

**Comment by atvanguard** [comment]
Not sure what this was about. Feel free to reopen with details.
